#!/usr/bin/env ruby

$LOAD_PATH.unshift File.expand_path("..", "lib/spec_reports_toolbox")

require "spec_reports_toolbox/test_run"
require "spec_reports_toolbox/test_run/failed_spec_log_printer"
require "slop"

begin
  opts = Slop.parse do |options|
    options.banner = "Usage: inspect_run.rb [options]"

    options.string "-r", "--run-id", "Run ID", required: true
    options.integer "-a", "--run-attempt", "Run Attempt", default: 1
    options.bool "-fa", "--fetch-artifacts", "Fetch artifacts from S3", default: false
    options.bool "-fr", "--fetch-reports", "Fetch reports from S3", default: false
    options.bool "-t", "--display-table", "Display table", default: false
    options.bool "-l", "--display-logs", "Display logs", default: false
    options.bool "--force", "Force artifacts to be deleted and re-fetched", default: false

    options.on "-h", "--help" do
      puts options
      exit
    end
  end

  test_run = TestRun.new(opts[:run_id], opts[:run_attempt])
  test_run.spec_artifacts.fetch!(force: opts[:force]) if opts[:fetch_artifacts]
  test_run.spec_reports.fetch!(force: opts[:force]) if opts[:fetch_reports]

  puts test_run.spec_reports.to_table if opts[:display_table]
  puts test_run.spec_artifacts.display_logs if opts[:display_logs]
rescue Slop::Error => error
  puts error
rescue TestRun::SpecReports::MissingSpecReports => error
  puts "Missing spec reports. Pass --fetch-reports and ensure run_id is valid"
rescue TestRun::SpecArtifacts::MissingSpecArtifacts => error
  puts "Missing spec artifacts. Pass --fetch-artifacts and ensure run_id is valid"
ensure
  puts "Done!"
end
